config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home', to: 'pages#home', as: 'home'
  get 'pages/kidspeak'
  get 'pages/wavebnb'
  get 'pages/download', as: :download

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV['DOMAIN'] || 'localhost:3000' }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def kidspeak
  end

  def wavebnb
  end

  def download
    send_file "#{Rails.root}/app/assets/images/FranciscoCambim-CV-WebDev.pdf", type: 'file/pdf', disposition: 'attachment'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Francisco Cambim | Web Developer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('pf-nobg.png') %>
    <script src="https://kit.fontawesome.com/3ed3f076ae.js" crossorigin="anonymous"></script>
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
<%# <script src="script.js"></script> %>
<%# <script src="form.js"></script> %>
<%# <script src="sidemenu.js"></script> %>

<div id="header">
  <div class="container">
    <nav id="nav">
      <ul id="sidemenu">
        <i class="fa-solid fa-xmark" onclick="closemenu()" style="color: #fff;"></i>
        <li><a href="/" onclick="closemenu()">HOME</a></li>
        <li><a href="#about" onclick="closemenu()">ABOUT ME</a></li>
        <li><a href="#services" onclick="closemenu()">SKILLS</a></li>
        <li><a href="#projects" onclick="closemenu()">PROJECTS</a></li>
        <li><a href="#contact" onclick="closemenu()">CONTACT ME</a></li>
      </ul>
      <i class="fa-solid fa-bars" onclick="openmenu()" style="color: #fff;"></i>
    </nav>
    <div class="header-text">
      <h1>Hi, <span>Francisco</span> here.</h1>
      <p id="sub-header">I'm a Full Stack Web Developer</p>
    </div>
  </div>
</div>

<!-- About Section -->

<div id="about">
  <div class="container">
    <div class="row">
      <div class="about-col-1">
        <h1 class="sub-title">ABOUT ME</h1>
        <div id="about-description">
          <p>I'm passionate for coding and enjoy developing new, clean and beautiful web applications. My experience in marketing also makes me knowledgeable in how search engines and online communities function, helping me with not only developing an appealing product but also making sure it reaches its audience.</p>
          <br>
          <p>🛠 Here is what I can do for you:</p>
          <ul>
            <li>Develop functional web applications, using tools such as Javascript, JS frameworks (e.g. React) and HTML to build the frontend and tools such as Ruby or Python for the backend.</li>
            <li>Use CSS to make it look pixel perfect according to your needs or provide creative UI, using tools such as Figma.</li>
            <li>Build a solid database using SQL(PostgreSQL), ensuring its functionality and maintenance.</li>
            <li>Make sure a product reaches its target audience through SEO, boosting organic search results.</li>
            <li>Create user journey maps and user flows, considering potential users and their goals and pains.</li>
          </ul>
        </div>
      </div>
      <div class="about-col-2">

        <div class="tab-titles">
          <p class="tab-links active-link" onclick="opentab('skills')">TECH STACK</p>
          <p class="tab-links" onclick="opentab('experience')">EXPERIENCE</p>
          <p class="tab-links" onclick="opentab('education')">EDUCATION</p>
          <p class="tab-links" onclick="opentab('languages')">LANGUAGES</p>
        </div>
        <div class="tab-contents active-tab" id="skills">
          <ul>
            <li id="tech"><%= image_tag "js.png", alt:"js" %><span>JAVASCRIPT</span></li>
            <li id="tech"><%= image_tag "ruby.png", alt:"ruby" %><span>RUBY ON RAILS</span></li>
            <li id="tech"><%= image_tag "react.png", alt:"react" %><span>REACT</span></li>
            <li id="tech"><%= image_tag "html.png", alt:"html" %><span>HTML</span></li>
            <li id="tech"><%= image_tag "css.png", alt:"css" %><span>CSS</span></li>
            <li id="tech"><%= image_tag "python.png", alt:"python" %><span>PYTHON</span></li>
            <li id="tech"><%= image_tag "sql.png", alt:"sql" %><span>SQL</span></li>
            <li id="tech"><%= image_tag "bootstrap.svg", alt:"bootstrap" %><span>BOOTSTRAP</span></li>
            <li id="tech"><%= image_tag "git.svg", alt:"git" %><span>GIT</span></li>
            <li id="tech"><%= image_tag "postgresql.svg", alt:"postgresql" %><span>POSTGRESQL</span></li>
          </ul>
        </div>
        <div class="tab-contents" id="experience">
          <ul>
            <li><%= image_tag "MC.png", alt:"MC logo" %><br><span id="uni">Micro Clima</span><br><span>Communications Manager</span><br><p>Sep 2021 - Present</p></li>
            <li><%= image_tag "ks-big.png", alt:"Kidspeak logo" %><br><span id="uni">Kidspeak</span><br><span>Full Stack Web Developer</span><br><p>Jun 2023</p></li>
            <li><%= image_tag "boca.jpeg", alt:"BoCA logo" %><br><span id="uni">BoCA - Biennial of Contemporary Arts</span><br><span>Communications Manager</span><br><p>Feb 2022 - Mar 2023</p></li>
            <li><%= image_tag "fut.jpeg", alt:"Futurama logo" %><br><span id="uni">Futurama</span><br><span>Communications Manager</span><br><p>Mar 2022 - Mar 2023</p></li>
          </ul>
        </div>
        <div class="tab-contents" id="education">
          <ul>
            <li>
            <%= image_tag "lw.jpeg", alt:"LW logo" %><br>
            <span id="uni">Le Wagon</span><br>
            <span>Full Stack Web Development</span><br>
            <p>Apr 2023 - Jun 2023</p>
            <%= link_to "Diploma", "https://kitt.lewagon.com/schoolings/29737/public_diploma?token=b2140463d6a2cda0fabe1214a85381085d986f14a43c097420075cb24c58aa2b", target:"_blank", class:"btn btn2" %>
            </li>
            <li><%= image_tag "ucp.jpeg", alt:"UCP logo" %><br><span id="uni">Catholic University of Portugal</span><br><span>BA in Communication and Cultural Sciences</span><br><p>Sep 2015 - Jul 2018</p></li>
            <li><%= image_tag "wc.png", alt:"WC logo" %><br><span id="uni">World Academy</span><br><span>Technical Degree in Sound Engineering</span><br><p>Oct 2021 - Jul 2022</p></li>
          </ul>
        </div>
        <div class="tab-contents" id="languages">
          <ul>
            <li><span id="tech">PORTUGUESE</span>
              <div class="w3-light-grey">
                <div class="w3-container w3-center language-level">
                  <h4>NATIVE [ C2 ]</h4>
                </div>
              </div>
            </li>
            <li><span id="tech">ENGLISH</span>
              <div class="w3-light-grey">
                <div class="w3-container w3-center language-level">
                  <h4>FLUENT [ C2 ]</h4>
                </div>
              </div>
            </li>
            <li><span id="tech">SPANISH</span>
              <div class="w3-light-grey">
                <div class="w3-container w3-center language-level">
                  <h4>PROFESSIONAL PROFICIENCY [ C1 ]</h4>
                </div>
              </div>
            </li>
            <li><span id="tech">GERMAN</span>
              <div class="w3-light-grey">
                <div class="w3-container w3-center language-level">
                  <h4>PROFESSIONAL PROFICIENCY [ C1 ]</h4>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Services -->

<div id="services">
  <div class="container">
    <h1 class="centered-title">SKILLS</h1>
    <div class="services-list">
      <div>
        <i class="fa-solid fa-paint-roller"></i>
        <h2>FRONTEND DEVELOPMENT</h2>
        <!-- <p> Description for this service</p> -->
        <!-- <a href="#">Learn more</a> -->
      </div>
      <div>
        <i class="fa-solid fa-gears"></i>
        <h2>BACKEND DEVELOPMENT</h2>
        <!-- <p> Description for this service</p> -->
        <!-- <a href="#">Learn more</a> -->
      </div>
      <div>
        <i class="fa-brands fa-figma"></i>
        <h2>UX / UI</h2>
        <!-- <p> Description for this service</p> -->
        <!-- <a href="#">Learn more</a> -->
      </div>
    </div>
  </div>
</div>

<!-- Projects -->

<div id="projects">
  <div class="container">
    <h1 class="centered-title">PROJECTS</h1>
    <div class="work-list">
      <div class="work">
        <%= image_tag "ks.png", alt:"Kidspeak" %>
        <div class="layer">
          <h3>Kidspeak</h3>
          <p>A language-learning mobile application for migrant children, to help them learn the local language through a variety of games.</p>
          <div class="buttons">
            <%= link_to pages_kidspeak_path, class:"link-to" do %>
              <i class="fa-solid fa-circle-info fa-2xl"></i>
            <% end %>
            <%# <%= link_to "http://www.kidspeak.me", target:"_blank", class:"link-to" do %>
              <%# <i class="fa-solid fa-arrow-up-right-from-square fa-xl"></i> %>
            <%# <% end %>
          </div>
        </div>
      </div>
      <div class="work">
        <%= image_tag "wbnb.png", alt:"WaveBnB" %>
        <div class="layer">
          <h3>WaveBnB</h3>
          <p>A clone of AirBnB's website to rent surfboards, built in the context of Le Wagon's web development bootcamp.</p>
          <div class="buttons">
            <%= link_to pages_wavebnb_path, class:"link-to" do %>
              <i class="fa-solid fa-circle-info fa-2xl"></i>
            <% end %>
            <%# <%= link_to "https://airbnb-annarussi.herokuapp.com/", target:"_blank", class:"link-to" do %>
              <%# <i class="fa-solid fa-arrow-up-right-from-square fa-xl"></i> %>
            <%# <% end %>
          </div>
        </div>
      </div>
      <div class="work">
        <%= image_tag "whisper.png", alt:"Whisper" %>
        <div class="layer">
          <h3>Whisper</h3>
          <p>A chatroom designed to be a space where creative individuals can come together, exchange ideas, and collaborate on various artistic projects.</p>
          <!-- <a href="whisper.html" target="_blank"><i class="fa-solid fa-circle-info fa-2xl"></i></a> -->
          <p style="margin-top:30px; color:antiquewhite; font-size:30px;">COMING SOON</p>
        </div>
      </div>
    </div>
    <!-- <a href="#" class="btn">See more</a> -->
  </div>
</div>

<!-- Contact -->

<div id="contact">
  <div class="container">
    <div class="row">
      <div class="contact-left">
        <h1 class="sub-title contact-title">CONTACT ME</h1>
        <p><i class="fa-solid fa-paper-plane"></i>cambimfrancisco@gmail.com</p>
        <p><i class="fa-solid fa-mobile-screen-button"></i>+351 910285520</p>
        <div class="social-icons">
          <a href="https://www.linkedin.com/in/franciscocambim/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
          <a href="https://github.com/FMCambim" target="_blank"><i class="fa-brands fa-github"></i></a>
        </div>
        <%= link_to "DOWNLOAD CV", download_path, class:"btn btn2" %>

      </div>
      <div class="contact-right">
        <div class="contact-me">
          <form name="submit-to-google-sheet">
            <input placeholder="Name" class="form-input" type="text" name="Name" required/>
            <input name="Email" class="form-input" placeholder="Email" type="email" required/>
            <textarea name="Message" rows="6" placeholder="Your Message"></textarea>
            <button type="submit" class="submit-btn">SUBMIT</button>
          </form>
          <span id="msg"></span>
        </div>
      </div>
    </div>
  </div>
  <div class="copyright">
    <p id="copyright-text">Made with <i class="fa-solid fa-heart fa-beat fa-lg"></i> by Francisco Cambim</p>
  </div>
</div>

<script>
  const tablinks = document.getElementsByClassName("tab-links");
  const tabcontents = document.getElementsByClassName("tab-contents");

  function opentab(tabname){
    for(tablink of tablinks){
      tablink.classList.remove("active-link");
    }
    for(tabcontent of tabcontents){
      tabcontent.classList.remove("active-tab");
    }
    event.currentTarget.classList.add("active-link");
    document.getElementById(tabname).classList.add("active-tab");
  }
</script>

<script>
  let messageArray = ["I'm a Full Stack Web Developer."];
  let textPosition = 0;
  let speed = 50;

  typewriter = () => {
    document.querySelector("#sub-header").
    innerHTML = messageArray[0].substring(0,
    textPosition);

    if(textPosition++ != messageArray[0].length)
      setTimeout(typewriter, speed);
  }

  window.addEventListener("load", typewriter);
</script>

<script>
const sidemenu = document.getElementById("sidemenu");

function openmenu(){
  sidemenu.style.right = "0";
}
function closemenu(){
  sidemenu.style.right = "-230px";
}
</script>

<script>
const scriptURL = 'https://script.google.com/macros/s/AKfycbzV9OmCTi364g1425T25kOaWguJrYK_V4EytzIc-bcgb6KPK1mAr63QeN5D_M37N3Uz/exec'
const form = document.forms["submit-to-google-sheet"]
const msg = document.getElementById("msg")

form.addEventListener('submit', e => {
  e.preventDefault()
  fetch(scriptURL, { method: 'POST', body: new FormData(form)})
    .then(response => {
      msg.innerHTML = "Message sent successfully!"
      setTimeout(function(){
        msg.innerHTML = ""
      }, 3000);
      form.reset()
    })
    .catch(error => console.error('Error!', error.message))
})
</script>

app/views/pages/kidspeak.html.erb
<%= stylesheet_link_tag 'application' %>
<script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
<script src="video.js"></script>

<div class="container" style="display:flex;align-items:center;justify-content:center;">
  <%= link_to home_path, class:"kidspeak-nav" do %>
    <i class="fa-solid fa-house fa-lg"></i>
  <% end %>
</div>

<!-- Kidspeak Section -->

<div id="about" style="margin-top:-20px;;margin-bottom:-40x;">
  <div class="container">
    <div class="row">
      <div class="about-col-1">
        <h1 class="sub-title">TECH STACK</h1>
        <div class="tab-titles">
          <p class="tab-links active-link" onclick="opentab('skills')">BACKEND</p>
          <p class="tab-links" onclick="opentab('experience')">FRONTEND</p>
        </div>
        <div class="tab-contents active-tab" id="skills">
          <ul>
            <li id="tech"><span><svg style="color: rgb(205, 60, 24); margin-right:10px;" width="25px" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Ruby</title><path d="M20.156.083c3.033.525 3.893 2.598 3.829 4.77L24 4.822 22.635 22.71 4.89 23.926h.016C3.433 23.864.15 23.729 0 19.139l1.645-3 2.819 6.586.503 1.172 2.805-9.144-.03.007.016-.03 9.255 2.956-1.396-5.431-.99-3.9 8.82-.569-.615-.51L16.5 2.114 20.159.073l-.003.01zM0 19.089zM5.13 5.073c3.561-3.533 8.157-5.621 9.922-3.84 1.762 1.777-.105 6.105-3.673 9.636-3.563 3.532-8.103 5.734-9.864 3.957-1.766-1.777.045-6.217 3.612-9.75l.003-.003z" fill="#cd3c18"></path></svg>RUBY ON RAILS</span></li>
            <li id="postgresql"><iconify-icon icon="logos:postgresql" style="margin-right:10px; margin-top:0px; margin-bottom:0px;" width="30px"></iconify-icon><p>POSTGRESQL</p></li>
            <li id="tech"><span><svg style="color: rgb(65, 0, 148); margin-right:10px;" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"> <path d="M27.479 0h-22.957c-1.604 0-2.881 1.281-2.881 2.88v26.24c0 1.599 1.277 2.88 2.881 2.88h22.957c1.6 0 2.881-1.281 2.881-2.88v-26.24c0-1.599-1.277-2.88-2.881-2.88zM28.76 29.12c0 0.719-0.563 1.281-1.281 1.281h-22.957c-0.719 0-1.281-0.563-1.281-1.281v-26.24c0-0.719 0.563-1.281 1.281-1.281h22.957c0.719 0 1.281 0.563 1.281 1.281zM8.839 27.197l3.599-3.197-3.599-3.197zM21.803 14.24c-0.641-0.641-1.839-1.437-3.839-1.437-2.161 0-4.401 0.557-6 1.119v-9.119h-3.204v13.837l2.24-1.041c0 0 3.683-1.677 6.88-1.677 1.599 0 2 0.881 2 1.677v9.599h3.203v-9.599c0.079-0.239 0.079-2-1.28-3.359zM17.563 10h3.197c1.437-1.683 2.161-3.36 2.401-5.197h-3.197c-0.324 1.837-1.125 3.515-2.401 5.197z" fill="#410094"></path> </svg>HEROKU</span></li>
          </ul>
        </div>
        <div class="tab-contents" id="experience">
          <ul>
            <li id="tech"><span><i class="fa-brands fa-square-js fa-xl"></i>JAVASCRIPT ES6</span></li>
            <li id="tech"><span><i class="fa-brands fa-html5 fa-xl"></i>HTML5</span></li>
            <li id="tech"><span><i class="fa-brands fa-css3-alt fa-xl"></i>CSS</span></li>
          </ul>
        </div>
      </div>
      <div class="about-col-2">
        <h1 class="sub-title">ABOUT</h1>
        <p id="about-description"> During the final 2 weeks of Le Wagon's Web Development Bootcamp, I embarked on an ambitious project, along with a team of colleagues, to develop a laguage-learning mobile app, aimed at helping immigrant children learn the local language through a variety of games.</p>
        <p id="about-description">The core objective of KidSpeak was to make language learning fun and accessible. The idea is to engage young learners with interactive games, visual aids, and audio pronunciation guides. By making the learning process interactive and entertaining, we aimed to foster a positive attitude towards language acquisition and encourage regular practice.</p>
        <p id="about-description" style="margin-bottom:30px;">I was involved in it from start to finish, helping to design, code, implement and ship to production, within a very collaborative and fruitful working environment.</p>
      </div>
    </div>
  </div>
</div>

<div class="container" id="wbnb-video">
  <h1 class="centered-title" style="margin-bottom: 50px;">USER JOURNEY</h1>
  <div class="row-bnb">
    <div class="video-player">
      <%= video_tag "ks-video.mp4", class:"video" %>

      <div class="player-controls">

        <div class="video-progress">
          <div class="video-progress-filled"></div>
        </div>

        <button class="play-button" title="Play"><i class="fa-solid fa-play"></i></button>
        <i class="volume-icon fa-solid fa-volume-low fa-lg"></i>
        <input type="range" class="volume" min="0" max="1" step="0.01" value='1'>
        <div class="time">
          <span class="current">0:00</span> / <span class="duration">0:00</span>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="projects">
  <div class="container">
    <h1 class="centered-title">MAIN PAGES</h1>
    <div class="work-list">
      <div class="work">
        <%= image_tag "ks-1.png", alt: "Photo1" %>
        <div class="layer">
          <h3 style="font-size:30px; margin-bottom:60px;">Player's Profile Page</h3>
          <p style="font-size:20px;">Here the player can see the unlocked treasures + the current level and score.</p>
        </div>
      </div>
      <div class="work">
        <%= image_tag "ks-2.png", alt: "Photo2" %>
        <div class="layer">
          <h3 style="font-size:30px; margin-bottom:60px;">Treasure Map</h3>
          <p style="font-size:20px;">Here the player can find the all the treasure chests and games to be played.</p>
        </div>
      </div>
      <div class="work">
        <%= image_tag "ks-3.png", alt: "Photo3" %>
        <div class="layer">
          <h3 style="font-size:30px; margin-bottom:60px;">Avatar Page</h3>
          <p style="font-size:20px;">Here the player can choose the avatar. New ones will be added each time a challenge is completed.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="copyright-alt-page">
  <p id="copyright-text">Made with <i class="fa-solid fa-heart fa-beat fa-lg"></i> by Francisco Cambim</p>
</div>

<script>
  const tablinks = document.getElementsByClassName("tab-links");
  const tabcontents = document.getElementsByClassName("tab-contents");
  function opentab(tabname){
    for(tablink of tablinks){
      tablink.classList.remove("active-link");
    }
    for(tabcontent of tabcontents){
      tabcontent.classList.remove("active-tab");
    }
    event.currentTarget.classList.add("active-link");
    document.getElementById(tabname).classList.add("active-tab");
  }
</script>

<script>
const videoPlayer = document.querySelector('.video-player')
const video = videoPlayer.querySelector('.video')
const playButton = videoPlayer.querySelector('.play-button')
const volume = videoPlayer.querySelector('.volume')
const currentTimeElement = videoPlayer.querySelector('.current')
const durationTimeElement = videoPlayer.querySelector('.duration')
const progress = videoPlayer.querySelector('.video-progress')
const progressBar = videoPlayer.querySelector('.video-progress-filled')

//Play and Pause button

playButton.addEventListener('click', (e) => {
  if(video.paused) {
    video.play()
    playButton.innerHTML = '<i class="fas fa-pause"></i>'
  } else {
    video.pause()
    playButton.innerHTML = '<i class="fas fa-play"></i>'
  }
})


//Volume
volume.addEventListener('mousemove', (e) => {
  video.volume = e.target.value
})

//Progress bar

const currentTime = () => {
  let currentMinutes = Math.floor(video.currentTime / 60)
  let currentSeconds = Math.floor(video.currentTime - currentMinutes * 60)
  let durationMinutes = Math.floor(video.duration / 60)
  let durationSeconds = Math.floor(video.duration - durationMinutes * 60)

  currentTimeElement.innerHTML = `${currentMinutes}:${currentSeconds < 10 ? '0' + currentSeconds : currentSeconds}`
  durationTimeElement.innerHTML = `${durationMinutes}:${durationSeconds}`
}

video.addEventListener('timeupdate', currentTime)

//Progress bar
video.addEventListener('timeupdate', () => {
  const percentage = (video.currentTime / video.duration) * 100
  progressBar.style.width = `${percentage}%`
})

// change progress bar on click
progress.addEventListener('click', (e) => {
  const progressTime = (e.offsetX / progress.offsetWidth) * video.duration
  video.currentTime = progressTime
})
</script>